/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.spica.expressionj;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
